### PR TITLE
crdb_main_test.go.tpl: added DB url string for every command execution

### LINKED ISSUE #20: Unable to run sqlboiler model's testcases when the cockroachdb is running as a docker component.
I'm trying to run CockroachDB model's test cases where the cockroach server is running as a docker container.
Error Response:
```bash
2019-02-01T12:49:29.9360465Z failed running: cockroach [sql --insecure --execute DROP DATABASE IF EXISTS dedvaktnvuarqtsykzrfvmjmnrmjyzgjwneslvue CASCADE]
2019-02-01T12:49:29.9360787Z 
2019-02-01T12:49:29.9360883Z Error: cannot dial server.
2019-02-01T12:49:29.9361038Z Is the server running?
2019-02-01T12:49:29.9361705Z If the server is running, check --host client-side and --advertise server-side.
```
CockroachDB's binary is unavailable in this case.
 
Why is the in built cockroachdb sql Client binary is used here instead of `dbConn` which is already a part of `crdbTester`?

```go
type crdbTester struct {
	dbConn *sql.DB

	dbName  string
	host    string
	user    string
	pass    string
	sslmode string
	port    int

	testDBName string
}
```

```go
func (c *crdbTester) createTestDB() error {
  stmt := fmt.Sprintf("CREATE DATABASE %s", c.testDBName)
  //why not db.Exec("CREATE DATABASE " + databaseName)
  return c.runCmd("", "cockroach", "sql", "--insecure", "--execute", stmt) }
```

https://github.com/glerchundi/sqlboiler-crdb/blob/0d1e315460fb22f7df552f710caf89a7f083470c/driver/override/templates_test/singleton/crdb_main_test.go.tpl#L96

### PR DESCRIPTION
**Pull request by glerchundi**
Closes #20

### CODE REVIEW

**Comment by glerchundi** [comment]
@themontem I'm going to apply these changes myself as I'm using a different version of go-bindata which does output a different result than yours.

If you agree i will merge this one. Thanks for the contributing and sorry for the loooong delay :(

**Comment by themontem** [comment]
@glerchundi No issue, we can merge this one. Thanks for asking.

**Comment by themontem** [comment]
Can you add the version of go-bindata to README, as that's the only external tool?

**Comment by glerchundi** [comment]
> @glerchundi No issue, we can merge this one. Thanks for asking.

Fantastic, thanks for the contribution!

> Can you add the version of go-bindata to README, as that's the only external tool?

Sure.

**Comment by glerchundi** [comment]
This commit should be enough to avoid this from happening again: https://github.com/glerchundi/sqlboiler-crdb/commit/f175c13b8bb523dcb0ca400ebd4b5e6150e89269

**Pull request merged**
