### PR TITLE
Update rgxCDBFkey to fix test cases for crdb binary v2.1.0

### PR DESCRIPTION
**Pull request by themontem**
- [x] Update rgxCDBFkey 
> In order to fix all cases of this, remove FKs from create statements and move them to ALTERs below.
https://github.com/cockroachdb/cockroach/commit/65c0bfbd64ca6d92ac3d2c655415a0d1433586d6

### CODE REVIEW

**Comment by glerchundi** [comment]
I'm going to keep this change on-hold. I would like to add CI and integration tests so that this incompatibility issues don't happen anymore.

**Comment by themontem** [comment]
Removed changes in `crdb.go`, but we need changes for `rgxCDBFkey`, as commit cockroachdb/cockroach@65c0bfb is merged in v2.1.0-alpha.20180507.

**Comment by glerchundi** [comment]
Ok, will merge if it's hurting you with a two conditions ;)
1. Although it seems you take into account older versions (due to the conditional part of the regex), can you confirm that 2.0 is still working?
2. Change the commit as well as the PR title to something that relates to tests in CRDB 2.1.

**Comment by themontem** [comment]
Update commit message and tested changes with:

```
Build Tag:    v2.0.6
Build Time:   2018/10/01 14:06:38
Distribution: CCL
Platform:     windows amd64 (x86_64-w64-mingw32)
Go Version:   go1.10
C Compiler:   gcc 6.3.0
Build SHA-1:  d30787727998a453fcae13c5a0c90f27f02a69f2
Build Type:   release
```

```
Build Tag:    v2.1.0
Build Time:   2018/10/30 12:40:27
Distribution: CCL
Platform:     windows amd64 (x86_64-w64-mingw32)
Go Version:   go1.10.3
C Compiler:   gcc 6.3.0
Build SHA-1:  f0dd1dc2d2500155c8b36330ae3d6932c13c1027
Build Type:   release
```

**Comment by glerchundi** [comment]
Thanks @themontem

**Pull request merged**
