### PR TITLE
*: migrate to modules, bump sqlboiler to latest

### PR DESCRIPTION
**Pull request by lopezator**
migrate to golang modules, deprecate dep. bump sqlboiler to latest

### CODE REVIEW

**Comment by glerchundi** [comment]
Planning to merge, as this change was made back in September. Does this require something else or do you think it's ok as is?

**Comment by lopezator** [comment]
A couple of updates could be done if you are ok with them:

- first, update sqlboiler to the latest stable version, 3.6.1
- second, put go.mod in go 1.13 mode here: https://github.com/glerchundi/sqlboiler-crdb/pull/25/files#diff-37aff102a57d3d7b797f152915a6dc16R3

**Comment by lopezator** [comment]
PTAL

**Comment by glerchundi** [comment]
Thanks!

**Pull request merged**
