### PR TITLE
Enum data types

### PR DESCRIPTION
**Pull request by optiman**
Enums are added in CockroachDB v20.2 which is already RC2.
https://www.cockroachlabs.com/docs/v20.2/enum.html

For versions < v20.2 this change will gracefully do nothing.

### CODE REVIEW

**Comment by glerchundi** [comment]
Thanks for the contribution & sorry for the delay. I found a free slot for the next week I wanted to just let you know.

**Comment by optiman** [comment]
In `v20.2.2` owner column was added to `SHOW ENUMS` statement.
Updated the code to support this.

**Comment by optiman** [comment]
Updated enum values parsing to support upcoming `v21.1.0` (https://github.com/cockroachdb/cockroach/pull/55386)

**Comment by optiman** [comment]
I'm going to close this PR since this repository obviously is abandoned and my `master` branch already has more changes than is needed for this PR.
If someone temporarily used my fork, please lock the commit hash in your `go.mod`, because `master` branch will not necessarily be backwards compatible.

**Pull request closed without merging**
