### PR TITLE
fix bug with foreign keys being seen as unique

### PR DESCRIPTION
**Pull request by stephenafamo**

### CODE REVIEW

**Comment by glerchundi** [comment]
I don't have much time to invest on this so expect some time before getting this merged. Some time = 1-2 weeks.

**Comment by stephenafamo** [comment]
Okay, that's fine.

**Comment by glerchundi** [comment]
@stephenafamo sorry for the delay.

I fixed a bug in master where generated code doesn't keep the order it should meaning that it was very hard to keep an an eye on diffs.

Although it seems obvious, can you put before and after examples of what does this fixes? I can regenerate golden test once this gets merged so that the test passes.

Thanks,

**Comment by stephenafamo** [comment]
Ok.

Using this example schema, this is the diff in the produced user model. Note how it marks the relationship with posts as `*Post` instead of `PostSlice`


<details><summary>test-schema.sql</summary>

```sql
CREATE TABLE users (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	email STRING NULL,
	FAMILY "primary" (id, email)
);

CREATE TABLE posts (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	user_id UUID NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	content STRING NULL,
	FAMILY "primary" (id, user_id, content)
);

CREATE TABLE comments (
	user_id UUID NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	post_id UUID NULL REFERENCES posts (id) ON DELETE CASCADE ON UPDATE CASCADE,
	content STRING NULL,
	PRIMARY KEY (user_id, post_id),
	FAMILY "primary" (user_id, post_id, content)
);
```
</details>

<details><summary>users.go</summary>

```diff
43d42
< 	Post     string
44a44
> 	Posts    string
46d45
< 	Post:     "Post",
47a47
> 	Posts:    "Posts",
52d51
< 	Post     *Post
53a53
> 	Posts    PostSlice
306,309c306,310
< // Post pointed to by the foreign key.
< func (o *User) Post(mods ...qm.QueryMod) postQuery {
< 	queryMods := []qm.QueryMod{
< 		qm.Where("user_id=?", o.ID),
---
> // Comments retrieves all the comment's Comments with an executor.
> func (o *User) Comments(mods ...qm.QueryMod) commentQuery {
> 	var queryMods []qm.QueryMod
> 	if len(mods) != 0 {
> 		queryMods = append(queryMods, mods...)
312c313,315
< 	queryMods = append(queryMods, mods...)
---
> 	queryMods = append(queryMods,
> 		qm.Where("\"comments\".\"user_id\"=?", o.ID),
> 	)
314,315c317,322
< 	query := Posts(queryMods...)
< 	queries.SetFrom(query.Query, "\"posts\"")
---
> 	query := Comments(queryMods...)
> 	queries.SetFrom(query.Query, "\"comments\"")
> 
> 	if len(queries.GetSelect(query.Query)) == 0 {
> 		queries.SetSelect(query.Query, []string{"\"comments\".*"})
> 	}
320,321c327,328
< // Comments retrieves all the comment's Comments with an executor.
< func (o *User) Comments(mods ...qm.QueryMod) commentQuery {
---
> // Posts retrieves all the post's Posts with an executor.
> func (o *User) Posts(mods ...qm.QueryMod) postQuery {
328c335
< 		qm.Where("\"comments\".\"user_id\"=?", o.ID),
---
> 		qm.Where("\"posts\".\"user_id\"=?", o.ID),
331,332c338,339
< 	query := Comments(queryMods...)
< 	queries.SetFrom(query.Query, "\"comments\"")
---
> 	query := Posts(queryMods...)
> 	queries.SetFrom(query.Query, "\"posts\"")
335c342
< 		queries.SetSelect(query.Query, []string{"\"comments\".*"})
---
> 		queries.SetSelect(query.Query, []string{"\"posts\".*"})
341,343c348,350
< // LoadPost allows an eager lookup of values, cached into the
< // loaded structs of the objects. This is for a 1-1 relationship.
< func (userL) LoadPost(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUser interface{}, mods queries.Applicator) error {
---
> // LoadComments allows an eager lookup of values, cached into the
> // loaded structs of the objects. This is for a 1-M or N-M relationship.
> func (userL) LoadComments(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUser interface{}, mods queries.Applicator) error {
367c374
< 				if queries.Equal(a, obj.ID) {
---
> 				if a == obj.ID {
376c383
< 	query := NewQuery(qm.From(`posts`), qm.WhereIn(`user_id in ?`, args...))
---
> 	query := NewQuery(qm.From(`comments`), qm.WhereIn(`user_id in ?`, args...))
383c390
< 		return errors.Wrap(err, "failed to eager load Post")
---
> 		return errors.Wrap(err, "failed to eager load comments")
386c393
< 	var resultSlice []*Post
---
> 	var resultSlice []*Comment
388c395
< 		return errors.Wrap(err, "failed to bind eager loaded slice Post")
---
> 		return errors.Wrap(err, "failed to bind eager loaded slice comments")
392c399
< 		return errors.Wrap(err, "failed to close results of eager load for posts")
---
> 		return errors.Wrap(err, "failed to close results in eager load on comments")
395c402
< 		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for posts")
---
> 		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for comments")
398c405
< 	if len(userAfterSelectHooks) != 0 {
---
> 	if len(commentAfterSelectHooks) != 0 {
405,409d411
< 
< 	if len(resultSlice) == 0 {
< 		return nil
< 	}
< 
411,414c413,418
< 		foreign := resultSlice[0]
< 		object.R.Post = foreign
< 		if foreign.R == nil {
< 			foreign.R = &postR{}
---
> 		object.R.Comments = resultSlice
> 		for _, foreign := range resultSlice {
> 			if foreign.R == nil {
> 				foreign.R = &commentR{}
> 			}
> 			foreign.R.User = object
416c420
< 		foreign.R.User = object
---
> 		return nil
419,422c423,426
< 	for _, local := range slice {
< 		for _, foreign := range resultSlice {
< 			if queries.Equal(local.ID, foreign.UserID) {
< 				local.R.Post = foreign
---
> 	for _, foreign := range resultSlice {
> 		for _, local := range slice {
> 			if local.ID == foreign.UserID {
> 				local.R.Comments = append(local.R.Comments, foreign)
424c428
< 					foreign.R = &postR{}
---
> 					foreign.R = &commentR{}
435c439
< // LoadComments allows an eager lookup of values, cached into the
---
> // LoadPosts allows an eager lookup of values, cached into the
437c441
< func (userL) LoadComments(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUser interface{}, mods queries.Applicator) error {
---
> func (userL) LoadPosts(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUser interface{}, mods queries.Applicator) error {
461c465
< 				if a == obj.ID {
---
> 				if queries.Equal(a, obj.ID) {
470c474
< 	query := NewQuery(qm.From(`comments`), qm.WhereIn(`user_id in ?`, args...))
---
> 	query := NewQuery(qm.From(`posts`), qm.WhereIn(`user_id in ?`, args...))
477c481
< 		return errors.Wrap(err, "failed to eager load comments")
---
> 		return errors.Wrap(err, "failed to eager load posts")
480c484
< 	var resultSlice []*Comment
---
> 	var resultSlice []*Post
482c486
< 		return errors.Wrap(err, "failed to bind eager loaded slice comments")
---
> 		return errors.Wrap(err, "failed to bind eager loaded slice posts")
486c490
< 		return errors.Wrap(err, "failed to close results in eager load on comments")
---
> 		return errors.Wrap(err, "failed to close results in eager load on posts")
489c493
< 		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for comments")
---
> 		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for posts")
492c496
< 	if len(commentAfterSelectHooks) != 0 {
---
> 	if len(postAfterSelectHooks) != 0 {
500c504
< 		object.R.Comments = resultSlice
---
> 		object.R.Posts = resultSlice
503c507
< 				foreign.R = &commentR{}
---
> 				foreign.R = &postR{}
512,513c516,517
< 			if local.ID == foreign.UserID {
< 				local.R.Comments = append(local.R.Comments, foreign)
---
> 			if queries.Equal(local.ID, foreign.UserID) {
> 				local.R.Posts = append(local.R.Posts, foreign)
515c519
< 					foreign.R = &commentR{}
---
> 					foreign.R = &postR{}
526,529c530,534
< // SetPost of the user to the related item.
< // Sets o.R.Post to related.
< // Adds o to related.R.User.
< func (o *User) SetPost(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Post) error {
---
> // AddComments adds the given related objects to the existing relationships
> // of the user, optionally inserting them as new records.
> // Appends related to o.R.Comments.
> // Sets related.R.User appropriately.
> func (o *User) AddComments(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Comment) error {
530a536,548
> 	for _, rel := range related {
> 		if insert {
> 			rel.UserID = o.ID
> 			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
> 				return errors.Wrap(err, "failed to insert into foreign table")
> 			}
> 		} else {
> 			updateQuery := fmt.Sprintf(
> 				"UPDATE \"comments\" SET %s WHERE %s",
> 				strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
> 				strmangle.WhereClause("\"", "\"", 2, commentPrimaryKeyColumns),
> 			)
> 			values := []interface{}{o.ID, rel.UserID, rel.PostID}
532,544c550,553
< 	if insert {
< 		queries.Assign(&related.UserID, o.ID)
< 
< 		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
< 			return errors.Wrap(err, "failed to insert into foreign table")
< 		}
< 	} else {
< 		updateQuery := fmt.Sprintf(
< 			"UPDATE \"posts\" SET %s WHERE %s",
< 			strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
< 			strmangle.WhereClause("\"", "\"", 2, postPrimaryKeyColumns),
< 		)
< 		values := []interface{}{o.ID, related.ID}
---
> 			if boil.DebugMode {
> 				fmt.Fprintln(boil.DebugWriter, updateQuery)
> 				fmt.Fprintln(boil.DebugWriter, values)
> 			}
546,549c555,557
< 		if boil.DebugMode {
< 			fmt.Fprintln(boil.DebugWriter, updateQuery)
< 			fmt.Fprintln(boil.DebugWriter, values)
< 		}
---
> 			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
> 				return errors.Wrap(err, "failed to update foreign table")
> 			}
551,552c559
< 		if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
< 			return errors.Wrap(err, "failed to update foreign table")
---
> 			rel.UserID = o.ID
554,555d560
< 
< 		queries.Assign(&related.UserID, o.ID)
560c565
< 			Post: related,
---
> 			Comments: related,
563c568
< 		o.R.Post = related
---
> 		o.R.Comments = append(o.R.Comments, related...)
566,568c571,577
< 	if related.R == nil {
< 		related.R = &postR{
< 			User: o,
---
> 	for _, rel := range related {
> 		if rel.R == nil {
> 			rel.R = &commentR{
> 				User: o,
> 			}
> 		} else {
> 			rel.R.User = o
570,571d578
< 	} else {
< 		related.R.User = o
576,596c583
< // RemovePost relationship.
< // Sets o.R.Post to nil.
< // Removes o from all passed in related items' relationships struct (Optional).
< func (o *User) RemovePost(ctx context.Context, exec boil.ContextExecutor, related *Post) error {
< 	var err error
< 
< 	queries.SetScanner(&related.UserID, nil)
< 	if _, err = related.Update(ctx, exec, boil.Whitelist("user_id")); err != nil {
< 		return errors.Wrap(err, "failed to update local table")
< 	}
< 
< 	o.R.Post = nil
< 	if related == nil || related.R == nil {
< 		return nil
< 	}
< 
< 	related.R.User = nil
< 	return nil
< }
< 
< // AddComments adds the given related objects to the existing relationships
---
> // AddPosts adds the given related objects to the existing relationships
598c585
< // Appends related to o.R.Comments.
---
> // Appends related to o.R.Posts.
600c587
< func (o *User) AddComments(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Comment) error {
---
> func (o *User) AddPosts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Post) error {
604c591
< 			rel.UserID = o.ID
---
> 			queries.Assign(&rel.UserID, o.ID)
610c597
< 				"UPDATE \"comments\" SET %s WHERE %s",
---
> 				"UPDATE \"posts\" SET %s WHERE %s",
612c599
< 				strmangle.WhereClause("\"", "\"", 2, commentPrimaryKeyColumns),
---
> 				strmangle.WhereClause("\"", "\"", 2, postPrimaryKeyColumns),
614c601
< 			values := []interface{}{o.ID, rel.UserID, rel.PostID}
---
> 			values := []interface{}{o.ID, rel.ID}
625c612
< 			rel.UserID = o.ID
---
> 			queries.Assign(&rel.UserID, o.ID)
631c618
< 			Comments: related,
---
> 			Posts: related,
634c621
< 		o.R.Comments = append(o.R.Comments, related...)
---
> 		o.R.Posts = append(o.R.Posts, related...)
639c626
< 			rel.R = &commentR{
---
> 			rel.R = &postR{
645a633,702
> 	return nil
> }
> 
> // SetPosts removes all previously related items of the
> // user replacing them completely with the passed
> // in related items, optionally inserting them as new records.
> // Sets o.R.User's Posts accordingly.
> // Replaces o.R.Posts with related.
> // Sets related.R.User's Posts accordingly.
> func (o *User) SetPosts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Post) error {
> 	query := "update \"posts\" set \"user_id\" = null where \"user_id\" = $1"
> 	values := []interface{}{o.ID}
> 	if boil.DebugMode {
> 		fmt.Fprintln(boil.DebugWriter, query)
> 		fmt.Fprintln(boil.DebugWriter, values)
> 	}
> 
> 	_, err := exec.ExecContext(ctx, query, values...)
> 	if err != nil {
> 		return errors.Wrap(err, "failed to remove relationships before set")
> 	}
> 
> 	if o.R != nil {
> 		for _, rel := range o.R.Posts {
> 			queries.SetScanner(&rel.UserID, nil)
> 			if rel.R == nil {
> 				continue
> 			}
> 
> 			rel.R.User = nil
> 		}
> 
> 		o.R.Posts = nil
> 	}
> 	return o.AddPosts(ctx, exec, insert, related...)
> }
> 
> // RemovePosts relationships from objects passed in.
> // Removes related items from R.Posts (uses pointer comparison, removal does not keep order)
> // Sets related.R.User.
> func (o *User) RemovePosts(ctx context.Context, exec boil.ContextExecutor, related ...*Post) error {
> 	var err error
> 	for _, rel := range related {
> 		queries.SetScanner(&rel.UserID, nil)
> 		if rel.R != nil {
> 			rel.R.User = nil
> 		}
> 		if _, err = rel.Update(ctx, exec, boil.Whitelist("user_id")); err != nil {
> 			return err
> 		}
> 	}
> 	if o.R == nil {
> 		return nil
> 	}
> 
> 	for _, rel := range related {
> 		for i, ri := range o.R.Posts {
> 			if rel != ri {
> 				continue
> 			}
> 
> 			ln := len(o.R.Posts)
> 			if ln > 1 && i < ln-1 {
> 				o.R.Posts[i] = o.R.Posts[ln-1]
> 			}
> 			o.R.Posts = o.R.Posts[:ln-1]
> 			break
> 		}
> 	}
> 
```
</details>

**Comment by glerchundi** [comment]
@stephenafamo fixed in master, updated your branch to maintain you as the original contributor.

Thanks for your work and patience!

**Comment by stephenafamo** [comment]
Happy to help

**Pull request closed without merging**
